#pragma once

#include <sstream>
#include <string>
#include <utility>
#include <vector>

namespace chwell {
namespace codegen {

// ========== 轻量代码生成 ==========
//
// SchemaCodegen：从字段表生成 C++ Entity/Document 映射骨架，减少手写样板。
// - add_field(name, type)：type 为 int / int64 / double / bool / string
// - generate_entity(class_name, table_name) → 头文件级源码文本
//
// 生成结果是纯文本，由构建脚本落盘；不依赖运行时反射。

struct FieldSpec {
    std::string name;
    std::string type;  // "int"|"int64"|"double"|"bool"|"string"
};

class SchemaCodegen {
public:
    void add_field(const std::string& name, const std::string& type) {
        if (name.empty()) return;
        fields_.push_back({name, type});
    }

    void clear() { fields_.clear(); }

    const std::vector<FieldSpec>& fields() const { return fields_; }

    // 生成 PersistableEntity 派生类骨架
    std::string generate_entity(const std::string& class_name,
                                const std::string& table_name) const {
        std::ostringstream os;
        os << "// generated by SchemaCodegen — do not edit by hand\n";
        os << "#pragma once\n\n";
        os << "#include <string>\n\n";
        os << "#include \"chwell/storage/orm/writeback_cache.h\"\n\n";
        os << "class " << class_name
           << " : public chwell::storage::orm::PersistableEntity {\n";
        os << "public:\n";
        os << "    std::string table_name() const override { return \""
           << table_name << "\"; }\n";
        os << "    std::string id() const override { return "
           << (fields_.empty() ? std::string("id_") : member_name(fields_[0].name))
           << "; }\n\n";

        os << "    chwell::storage::orm::Document to_document() const override {\n";
        os << "        chwell::storage::orm::Document d;\n";
        for (const auto& f : fields_) {
            os << "        " << set_expr(f) << ";\n";
        }
        os << "        return d;\n";
        os << "    }\n\n";

        os << "    void from_document(const chwell::storage::orm::Document& d) override {\n";
        for (const auto& f : fields_) {
            os << "        " << get_expr(f) << ";\n";
        }
        os << "        clear_dirty();\n";
        os << "    }\n\n";

        os << "    // 字段访问器（set 自动打脏标）\n";
        for (const auto& f : fields_) {
            os << "    CHWELL_FIELD(" << cpp_type(f.type) << ", "
               << member_name(f.name) << ", " << f.name << ")\n";
        }

        os << "\nprivate:\n";
        for (const auto& f : fields_) {
            os << "    " << cpp_type(f.type) << " " << member_name(f.name)
               << default_init(f.type) << ";\n";
        }
        os << "};\n";
        return os.str();
    }

    // 生成 JSON 配置样例（便于对照）
    std::string generate_sample_json() const {
        std::ostringstream os;
        os << "{\n";
        for (std::size_t i = 0; i < fields_.size(); ++i) {
            const auto& f = fields_[i];
            os << "  \"" << f.name << "\": " << sample_value(f.type);
            if (i + 1 < fields_.size()) os << ",";
            os << "\n";
        }
        os << "}\n";
        return os.str();
    }

private:
    static std::string cpp_type(const std::string& t) {
        if (t == "int") return "int";
        if (t == "int64") return "std::int64_t";
        if (t == "double") return "double";
        if (t == "bool") return "bool";
        return "std::string";
    }

    static std::string member_name(const std::string& f) {
        return f + "_";
    }

    static std::string default_init(const std::string& t) {
        if (t == "string") return " = \"\"";
        return " = 0";
    }

    std::string set_expr(const FieldSpec& f) const {
        std::string m = member_name(f.name);
        if (f.type == "int") return "d.set_int(\"" + f.name + "\", " + m + ")";
        if (f.type == "int64") return "d.set_int64(\"" + f.name + "\", " + m + ")";
        if (f.type == "double") return "d.set_double(\"" + f.name + "\", " + m + ")";
        if (f.type == "bool") return "d.set_bool(\"" + f.name + "\", " + m + ")";
        return "d.set_string(\"" + f.name + "\", " + m + ")";
    }

    std::string get_expr(const FieldSpec& f) const {
        std::string m = member_name(f.name);
        std::string k = "\"" + f.name + "\"";
        if (f.type == "int") return m + " = d.get_int(" + k + ", " + m + ")";
        if (f.type == "int64") return m + " = d.get_int64(" + k + ", " + m + ")";
        if (f.type == "double") return m + " = d.get_double(" + k + ", " + m + ")";
        if (f.type == "bool") return m + " = d.get_bool(" + k + ", " + m + ")";
        return m + " = d.get_string(" + k + ", " + m + ")";
    }

    static std::string sample_value(const std::string& t) {
        if (t == "string") return "\"sample\"";
        if (t == "bool") return "true";
        if (t == "double") return "1.0";
        return "1";
    }

    std::vector<FieldSpec> fields_;
};

}  // namespace codegen
}  // namespace chwell
