find_package(PkgConfig QUIET)
if(PkgConfig_FOUND)
    pkg_check_modules(CHWELL_MONGO QUIET IMPORTED_TARGET GLOBAL libmongoc-1.0 libbson-1.0)
endif()
if(TARGET PkgConfig::CHWELL_MONGO)
    set(ChwellMongoDB_FOUND TRUE)
    if(NOT TARGET ChwellDependency::MongoDB)
        add_library(ChwellDependency::MongoDB INTERFACE IMPORTED GLOBAL)
        set_property(TARGET ChwellDependency::MongoDB PROPERTY INTERFACE_LINK_LIBRARIES PkgConfig::CHWELL_MONGO)
    endif()
else()
    find_path(CHWELL_MONGO_INCLUDE_DIR mongoc/mongoc.h PATH_SUFFIXES libmongoc-1.0)
    find_path(CHWELL_BSON_INCLUDE_DIR bson/bson.h PATH_SUFFIXES libbson-1.0)
    find_library(CHWELL_MONGO_LIBRARY NAMES mongoc-1.0)
    find_library(CHWELL_BSON_LIBRARY NAMES bson-1.0)
    include(FindPackageHandleStandardArgs)
    find_package_handle_standard_args(ChwellMongoDB REQUIRED_VARS
        CHWELL_MONGO_INCLUDE_DIR CHWELL_BSON_INCLUDE_DIR CHWELL_MONGO_LIBRARY CHWELL_BSON_LIBRARY)
    if(ChwellMongoDB_FOUND AND NOT TARGET ChwellDependency::MongoDB)
        add_library(ChwellDependency::MongoDB INTERFACE IMPORTED GLOBAL)
        set_target_properties(ChwellDependency::MongoDB PROPERTIES
            INTERFACE_LINK_LIBRARIES "${CHWELL_MONGO_LIBRARY};${CHWELL_BSON_LIBRARY}"
            INTERFACE_INCLUDE_DIRECTORIES "${CHWELL_MONGO_INCLUDE_DIR};${CHWELL_BSON_INCLUDE_DIR}")
    endif()
endif()
